### ISSUE TITLE
php Tutorials

### ISSUE THREAD

**Issue by Aeners** [grumbach/shopping#2]
[Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec egestas ipsum at metus mollis, ac iaculis enim consequat. Curabitur finibus ipsum tincidunt nulla malesuada, in ullamcorper purus viverra. Proin ultricies arcu eget nisi imperdiet, id ultricies odio placerat. In hac habitasse platea dictumst. Duis semper nibh purus, luctus volutpat nulla fringilla a. Sed volutpat bibendum ultricies. Vivamus vestibulum fermentum leo, sed dignissim tortor accumsan sit amet. Mauris tempus diam nisi, et commodo enim pretium non. Lorem ipsum dolor sit amet, consectetur adipiscing elit.](https://www.w3schools.com/php/)

**Comment by grumbach** [comment]
As they say : *Fight poison with poison*

Here you [go](https://github.com/KnpLabs/php-github-api/blob/master/doc/pull_requests.md)

```php
<?php

$pullRequest = $client->api('pull_request')->create('here', 'aeners', array(
    'base'  => 'master',
    'title' => '[ADD] some stuff for aeners',
));

>
```
